name: CloneProjectO1
description: ''
version: '1.0'
author: pankaj@prophecy.io
language: python
buildSystem: ''
buildSystemDetails:
  artefactID: cloneprojecto1
  parentArtefactID: pankajprophecyioteam
  buildSystem: wheel
  author: null
  createdAt: '2024-02-09 09:04:18'
pipelines:
  pipelines/pipeline01:
    name: pipeline01
    description: ''
    author: pankaj@prophecy.io
    mode: batch
    artefactID: ''
    language: python
    createdAt: '2024-02-09 09:04:18'
    datasets:
      inputs: []
      outputs: []
    subgraphs: []
    dependencies: {}
datasets: {}
templates: {}
jobs: {}
gemContainer:
  languageVersion: '3.10'
  gemLibsVersion: 1.3.4.0
  gems: {}
  dependencies: null
functions:
  author: null
  createdAt: '2024-02-09 09:04:18'
  udfs: {}
  udafs: {}
  expressions: {}
  airflowFunctions: {}
subgraphs: {}
sqlModels: {}
sqlMacros: {}
sqlSeeds: {}
sqlSources: {}
sqlUnreferencedSources: {}
sqlPipeline: null
dependencies: '[]'
projectDependencies:
  '33':
    projectUID: 33
    projectName: ProphecySparkBasicsPython
    repositoryPath: gitUri=http://gitserver:3000/DTAcEZUO_team_5/iaRHA2Zs_project_33.git&subPath=
    version: 0.2.3
    isDefault: true
    author: null
    createdAt: '2024-02-09 09:00:02'
  '34':
    projectUID: 34
    projectName: ProphecyWarehousePython
    repositoryPath: gitUri=http://gitserver:3000/DTAcEZUO_team_5/iaRHA2Zs_project_34.git&subPath=
    version: 0.0.2
    isDefault: true
    author: null
    createdAt: '2024-02-09 09:00:02'
flags:
  shouldAddDefaultDependenciesIfAbsent: true
pipelineConfigurations: {}
